### ISSUE TITLE
[Compare Lineages] Insertions caveat inconsistently displayed

### ISSUE THREAD

**Issue by EmilyHaag** [outbreak-info/outbreak.info#600] opened 2022-12-05 21:41 UTC
The red banner that describes the insertions caveat above the S gene compare lineages table disappears when you change lineages and select certain lineages. This seems like it happens for only the most recent lineages that were added because the caveat is there on the [default page](lineages):
![cl default](https://user-images.githubusercontent.com/75391907/205747997-75ef9f48-381a-4cea-9386-dc2b3f60a61b.png)

When I select [Omicron and sublineages](https://outbreak.info/compare-lineages?pango=Omicron&gene=S&threshold=75&sub=true&dark=false):
![cl omicron](https://user-images.githubusercontent.com/75391907/205748039-755a27cb-aa6a-4828-8cb6-494bfca61b98.png)

But disappears when selecting [BA.2.75*](https://outbreak.info/compare-lineages?pango=BA.2.75%2a%20%5BOmicron%20%28BA.2.75.X%29%5D&gene=S&threshold=75&sub=true&dark=false), BA.5*, or BQ.1*
![cl ba275](https://user-images.githubusercontent.com/75391907/205748066-a8349a5a-9b4e-45c9-84b3-1591c28cd457.png)

**Comment by flaneuse** [comment] 2022-12-14 00:19
@olekkorob : this is an issue because we search only if the lineage selected is "Omicron", not any of its descendants. Omicron descendant list is captured in `CURATED.filter(d => d.who_name == "Omicron").pango_descendants` (from the `curated_lineages.json`) file.

If the `pango` parameter is Omicron or any of the `pango_descendants` ("B.1.1.529","BA.1","BA.1.1","BA.1.1.1","BA.1.1.2","BA.1.1.3","BA.1.1.4","BA.1.1.5","BA.1.1.6","BA.1.1.7","BA.1.1.8","BA.1.1.9","BA.1.1.10","BA.1.1.11","BA.1.1.12","BA.1.1.13","BA.1.1.14","BA.1.1.15","BA.1.1.16","BA.1.1.17","BA.1.1.18","BA.1.2","BA.1.3","BA.1.4","BA.1.5","BA.1.6","BA.1.7","BA.1.8","BA.1.9","BA.1.10","BA.1.12","BA.1.13","BA.1.13.1","BA.1.14","BA.1.14.1","BA.1.14.2","BA.1.15","BA.1.15.1","BA.1.15.2","BA.1.15.3","BA.1.16","BA.1.16.1","BA.1.16.2" ...), this warning message should be displayed.

**Comment by olekkorob** [comment] 2022-12-14 17:25
Hi, @flaneuse , could you please try to reproduce this issue in your side? If you can, please let me know the steps how can I see this issue.

**Comment by flaneuse** [comment] 2022-12-14 17:59
Sure @olekkorob :

# Working as expected: 
the warning banner appears on the Omicron page:
[Omicron](https://outbreak.info/compare-lineages?pango=Omicron)
[Omicron + other lineages](https://outbreak.info/compare-lineages?pango=Omicron&pango=B.1)

# Not working as expected: 
a warning banner should appear on any page which includes a `pango` parameter which is one of `CURATED.filter(d => d.who_name == "Omicron").pango_descendants`, such as:

[BA.2.75*](https://outbreak.info/compare-lineages?pango=BA.2.75%2a%20%5BOmicron%20%28BA.2.75.X%29%5D&gene=S&threshold=75&sub=false&dark=false)
[BA.1.1.15](https://outbreak.info/compare-lineages?pango=BA.1.1.15)
[BA.1.1.15 and B.1](https://outbreak.info/compare-lineages?pango=BA.1.1.15&pango=B.1)

# This warning should not appear on other pages, such as:
[B.1.1.7](https://outbreak.info/compare-lineages?pango=B.1.1.7)
[B.1.1.7 and B.1](https://outbreak.info/compare-lineages?pango=B.1&pango=B.1.1.7)

**Comment by olekkorob** [comment] 2022-12-14 18:05
![image](https://user-images.githubusercontent.com/92925885/207672597-ec6f6918-7368-4364-a278-b3b8324c99d3.png)

In this case, warning should be shown?

**Comment by flaneuse** [comment] 2022-12-14 19:37
Yes, exactly.

**Comment by flaneuse** [comment] 2022-12-20 16:53
closed in #607

**Closed by flaneuse** 2022-12-20 16:53 UTC
Labels: bug, UX, guru
